### ISSUE TITLE
Générateur de nom

### ISSUE THREAD

**Issue by Dielos** [Richard-Degenne/irc_bot#1]
1. Le bot va sur https://en.m.wikipedia.org/wiki/Special:Random/#/random
2. Il cast le titre de l'article pour faire un beau pseudo (15 caractères max, pas de caractère spécial)
3. Il nous le donne, ou il nous renomme (s'il peut)
4. \o/

**Comment by Richard-Degenne** [comment]
Ça m'étonnerait qu'un utilisateur puisse en renommer un autre, mais je vais voir ça. :)

**Comment by Dielos** [comment]
Ouais non mais sinon il nous donne juste le nom :)
Wiktionnary d'ailleurs serai mieux c'est vrai

**Comment by Richard-Degenne** [comment]
Et voilà ! C'est mergé dans `develop`. Ça sera ajouté à `master` avec la release v0.2 !
